name: cb_intros
description: "A customizable and animated onboarding screen package for Flutter, allowing developers to quickly create beautiful introduction flows."
version: 0.2.2
homepage: https://github.com/connelevalsam/cb-intros
repository: https://github.com/connelevalsam/cb-intros

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  smooth_page_indicator: ^1.2.0+3
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:
  assets:
    - assets/images/test_img1.JPG
    - assets/images/test_img2.JPG

